"""Reproduce the numerical calibration reported in the manuscript.

The program checks the hybrid profile table, weighted ray-defect values,
positive-representation profiles, and the ``n=36`` worked example. Integer
roots and rational arithmetic are exact; rounding is used only for display.
"""
from fractions import Fraction
import math


def iroot(n, k):
    """Return the largest integer ``x`` such that ``x**k <= n``."""
    lo, hi = 0, 1
    while hi ** k <= n:
        hi *= 2
    while lo + 1 < hi:
        mid = (lo + hi) // 2
        if mid ** k <= n:
            lo = mid
        else:
            hi = mid
    return lo


def torus_norm(x, n):
    r = x % n
    return min(r, n - r)


def three_smooth_below(n):
    out = []
    a = 0
    while 2 ** a < n:
        b = 0
        while (2 ** a) * (3 ** b) < n:
            out.append((2 ** a) * (3 ** b))
            b += 1
        a += 1
    return sorted(set(out), reverse=True)


def fib_gaps(n):
    f = [1, 2]
    while f[-1] < n:
        f.append(f[-1] + f[-2])
    return [x for x in reversed(f) if x < n]


def semigroup_below(pref, n):
    """Return the semigroup generated by ``pref``, truncated to ``[0, n)``."""
    reach = {0}
    changed = True
    while changed:
        changed = False
        for g in pref:
            new = {s + g for s in reach if s + g < n} - reach
            if new:
                reach |= new
                changed = True
    return reach


def shortest_lengths(H, j, M):
    """Return shortest positive representation lengths on a ray window."""
    pref = H[: j - 1]
    target = H[j - 1]
    maxv = target * M
    best = {0: 0}
    frontier = [0]
    for step in range(1, 60):
        nxt = {}
        for s in frontier:
            for h in pref:
                v = s + h
                if v <= maxv and v not in best:
                    nxt[v] = step
        if not nxt:
            break
        best.update(nxt)
        frontier = list(nxt)
    return [best.get(target * m, float("inf")) for m in range(M + 1)]


def paper_rows():
    """Return displayed hybrid-profile rows for numerical comparison."""
    return [
        (10 ** 6, 6, 2, 1.111e-1, 1.602e-2, 6.9),
        (10 ** 9, 6, 2, 3.226e-2, 5.060e-4, 63.8),
        (10 ** 12, 6, 2, 1.010e-2, 1.600e-5, 631.3),
        (10 ** 12, 12, 2, 1.111e-1, 1.024e-3, 108.5),
    ]


def check_hybrid_calibration():
    print("=== Hybrid calibration: Fibonacci grid, exact lambda_j=2 chain ===")
    # The lambda_j = 2 transfer chain for H_F(n) follows from
    # h_j = h_{j-2} - h_{j-1} (j>=3), and h_j != +-h_i for all i<j, so the
    # signed l1 length is exactly 2 (check_calibration_consistency.py confirms this by exact
    # bounded-l1 minimization); N_j0 is the universal Dirichlet parameter
    # floor((n-1)^{1/j0}) from lem:dirichlet, independent of the gaps.
    ok = True
    for n, s, *_ in paper_rows():
        H = fib_gaps(n)
        assert H[-1] == 1 and len(H) > s
        for j in range(3, s + 1):
            assert H[j - 1] == H[j - 3] - H[j - 2], \
                f"fib chain h_{j} != h_{j-2}-h_{j-1} at n={n}"
        print(f"  n=1e{int(math.log10(n)):<3d} s={s:2d}: h_j = h_{'{j-2}'} - h_{'{j-1}'} "
              f"holds for j=3..{s} (lambda_j = 2 exactly)")
    for n, s, j0_paper, d_paper, h_paper, g_paper in paper_rows():
        Ns = iroot(n - 1, s)
        dirich = Fraction(1, Ns)
        best = None
        for j0 in range(2, s + 1):
            B = min(Fraction(1, 2), Fraction(2 ** (s - j0), iroot(n - 1, j0)))
            if best is None or B < best[1]:
                best = (j0, B)
        j0, B = best
        gain = dirich / B
        rel = lambda a, b: abs(a - b) <= 5e-4 * max(1.0, abs(b))
        # dirich/hybrid are displayed with three significant digits; gain with one decimal
        row_ok = (rel(float(dirich), d_paper) and rel(float(B), h_paper)
                  and abs(float(gain) - g_paper) <= 0.05 and j0 == j0_paper)
        ok &= row_ok
        print(f"  n=1e{int(math.log10(n)):<3d} s={s:2d} j0*={j0} "
              f"Dirichlet={float(dirich):.3e} Hybrid={float(B):.3e} "
              f"gain={float(gain):.1f}x "
              f"{'OK' if row_ok else 'MISMATCH'}")
    return ok


def check_weighted_calibration():
    print("\n=== Weighted calibration data: n=1000 ===")
    n = 1000
    paper = {
        ("Pratt", 162): (1, 838, 838), ("Pratt", 108): (1, 892, 892),
        ("Pratt", 81): (1, 919, 919), ("Pratt", 54): (1, 946, 946),
        ("Fibonacci", 610): (1, 390, 390), ("Fibonacci", 233): (4, 1670, 1670),
        ("Fibonacci", 89): (11, 5126, 5126), ("Fibonacci", 34): (29, 14210, 14210),
        ("Fibonacci", 13): (27, 22086, 20812),
    }
    ok = True
    for name, H in (("Pratt", three_smooth_below(n)), ("Fibonacci", fib_gaps(n))):
        for h in sorted({h for (nm, h) in paper if nm == name}):
            j = H.index(h) + 1
            M = (n - 1) // h
            reach = semigroup_below(H[: j - 1], n)
            G = [m for m in range(1, M + 1) if m * h not in reach]
            g = len(G)
            D = sum(n - m * h for m in G)
            sharp = n * g - h * g * (g + 1) // 2
            exp_g, exp_sharp, exp_D = paper[(name, h)]
            row_ok = (g == exp_g and sharp == exp_sharp and D == exp_D)
            ok &= row_ok
            print(f"  {name:9s} h={h:4d} g={g:2d} ng={n*g:5d} "
                  f"sharpened={sharp:5d} D={D:5d} {'OK' if row_ok else 'MISMATCH'}")
    return ok


def check_representation_profiles():
    print("\n=== Positive-representation profiles at n=1000 ===")
    n = 1000
    Pratt = three_smooth_below(n)
    Fib = fib_gaps(n)
    ok = True

    # Pratt panel: h=54, m=0..18
    j = Pratt.index(54) + 1
    prof = shortest_lengths(Pratt, j, 18)
    paper_blue = [(0, 0), (2, 1), (3, 1), (4, 1), (5, 2), (6, 1), (7, 2),
                  (8, 1), (9, 1), (10, 2), (11, 2), (12, 1), (13, 2), (14, 2),
                  (15, 2), (16, 1), (17, 2), (18, 1)]
    blue = [(m, int(x)) for m, x in enumerate(prof) if x != float("inf")]
    red = [m for m, x in enumerate(prof) if x == float("inf")]
    p_ok = (blue == paper_blue and red == [1])
    ok &= p_ok
    print(f"  Pratt h=54: blue={len(blue)} pts, missing={red} {'OK' if p_ok else 'MISMATCH'}")

    # Fibonacci panel: h=13, m=0..76
    j = Fib.index(13) + 1
    prof = shortest_lengths(Fib, j, 76)
    paper_blue = [(0, 0), (21, 13), (22, 12), (23, 11), (24, 9), (25, 8), (26, 6),
                  (27, 5), (28, 4), (29, 1), (30, 4), (31, 6), (32, 9),
                  (33, 11), (34, 13), (42, 26), (43, 25), (44, 24), (45, 22),
                  (46, 21), (47, 19), (48, 18), (49, 17), (50, 14), (51, 13),
                  (52, 12), (53, 10), (54, 9), (55, 6), (56, 5), (57, 4),
                  (58, 2), (59, 4), (60, 6), (61, 10), (62, 12), (63, 14),
                  (64, 17), (65, 19), (66, 22), (67, 24), (68, 26), (69, 31),
                  (70, 30), (71, 27), (72, 26), (73, 25), (74, 23), (75, 22),
                  (76, 19)]
    paper_red = list(range(1, 21)) + list(range(35, 42))
    blue = [(m, int(x)) for m, x in enumerate(prof) if x != float("inf")]
    red = [m for m, x in enumerate(prof) if x == float("inf")]
    f_ok = (blue == paper_blue and red == paper_red)
    ok &= f_ok
    print(f"  Fibonacci h=13: blue={len(blue)} pts, missing={len(red)} "
          f"{'OK' if f_ok else 'MISMATCH'}")
    return ok


def check_worked_example():
    print("\n=== Worked example (n=36, h_j=6) ===")
    H = [32, 27, 24, 18, 16, 12, 9, 8, 6]
    j = H.index(6) + 1
    reach = semigroup_below(H[: j - 1], 36)
    Q = [m for m in range(0, 6) if 6 * m in reach]
    G = [m for m in range(1, 6) if m not in Q]
    # lambda_j: 6 = 18 - 12
    lam = 2 if 18 in H[: j - 1] and 12 in H[: j - 1] else None
    ok = (2 in Q and 3 in Q and G == [1] and lam == 2)
    print(f"  Q_6 contains 2,3: {2 in Q and 3 in Q}; missing multipliers: {G} "
          f"(genus {len(G)} < LB=3); lambda_j={lam}")
    print(f"  {'OK' if ok else 'MISMATCH'}")
    return ok


if __name__ == "__main__":
    results = [
        check_hybrid_calibration(),
        check_weighted_calibration(),
        check_representation_profiles(),
        check_worked_example(),
    ]
    print("\n" + ("ALL OK" if all(results) else "MISMATCHES FOUND"))
    raise SystemExit(0 if all(results) else 1)
