"""Shared exact-arithmetic, semigroup, and Shellsort utilities.

Positions are zero-indexed, permutations contain ``0, ..., n-1``, and all
semigroup generators are positive integers. Reachability computations are
explicitly truncated at the bound supplied by each check.
"""
from collections import deque
from fractions import Fraction
import math
import random


# Numerical semigroups

def sg_reach(gens, N):
    """Return semigroup reachability on the integer interval ``[0, N]``."""
    reach = [False] * (N + 1)
    reach[0] = True
    for x in range(N + 1):
        if reach[x]:
            for g in gens:
                if 0 < g and x + g <= N:
                    reach[x + g] = True
    return reach


def genus_of(gens, N=8000):
    """Return the numerical-semigroup genus within a sufficient cutoff."""
    r = sg_reach(gens, N)
    return sum(1 for x in range(1, N + 1) if not r[x])


def frobenius_of(gens, N=8000):
    """Return the Frobenius number within a sufficient cutoff."""
    r = sg_reach(gens, N)
    return max(x for x in range(1, N + 1) if not r[x])


def apery_set(gens, a, N=6000):
    """Return the least reachable value in every residue class modulo ``a``."""
    r = sg_reach(gens, N)
    v = {}
    for res in range(a):
        m = None
        x = res
        while x <= N:
            if r[x]:
                m = x
                break
            x += a
        v[res] = m
    return v

# Shellsort

def gapped_insertion(a, h):
    """Apply one standard gapped-insertion pass and count h-step exchanges."""
    a = list(a)
    n = len(a)
    ex = 0
    for i in range(h, n):
        v = a[i]
        j = i
        while j >= h and a[j - h] > v:
            a[j] = a[j - h]
            j -= h
            ex += 1
        a[j] = v
    return a, ex


def is_dsorted(a, d):
    """Return whether ``a[i] <= a[i+d]`` whenever both positions exist."""
    return all(a[i] <= a[i + d] for i in range(len(a) - d))


def shellsort_counts(a, H):
    """Apply a decreasing gap sequence and return pass counts and output."""
    a = list(a)
    Ts = []
    for h in H:
        a, ex = gapped_insertion(a, h)
        Ts.append(ex)
    return Ts, a

# Directed certificates

def D_j(n, H, j):
    """Return the weighted ray defect ``D_j(n)`` for a one-indexed pass."""
    hj = H[j - 1]
    Mj = (n - 1) // hj
    prev = H[: j - 1]
    r = sg_reach(prev, n) if prev else [x == 0 for x in range(n + 1)]
    tot = 0
    for m in range(1, Mj + 1):
        if not r[m * hj]:
            tot += n - m * hj
    return tot


def U_s(n, H, s):
    """Return the residual positive-semigroup hole mass after ``s`` passes."""
    prev = H[:s]
    r = sg_reach(prev, n) if prev else [x == 0 for x in range(n + 1)]
    return sum(n - d for d in range(1, n) if not r[d])

# Additional exact utilities

def tnorm(x):
    """Return the distance from ``x`` to the nearest integer."""
    f = x - math.floor(x)
    return min(f, 1 - f)


def grid(A, n):
    """Return the full multiplicative grid generated by ``A`` below ``n``."""
    vals = {1}
    frontier = {1}
    while frontier:
        nf = set()
        for v in frontier:
            for a in A:
                if v * a < n:
                    nf.add(v * a)
        nf -= vals
        vals |= nf
        frontier = nf
    return sorted(vals, reverse=True)

def nrm(x, n):
    """Return the exact torus norm of ``x/n`` as a ``Fraction``."""
    r = x % n
    return Fraction(min(r, n - r), n)


def delta_max(H, j, k, n):
    """Return the maximum phase defect on the first ``j`` gaps."""
    return max(nrm(k * H[i], n) for i in range(j))


def signed_len(target, gens, window):
    """Return a shortest signed representation found by bounded BFS.

    The result is ``(length, witness)``. A search window that is too small can
    miss a representation, so callers use this routine only conservatively.
    """
    if target == 0:
        return 0, [0] * len(gens)
    dist = {0: (0, None, None)}
    dq = deque([0])
    while dq:
        u = dq.popleft()
        du = dist[u][0]
        for i, g in enumerate(gens):
            for sgn in (1, -1):
                v = u + sgn * g
                if v < -window or v > window or v in dist:
                    continue
                dist[v] = (du + 1, u, (i, sgn))
                if v == target:
                    x = [0] * len(gens)
                    cur = v
                    while dist[cur][1] is not None:
                        i2, s2 = dist[cur][2]
                        x[i2] += s2
                        cur = dist[cur][1]
                    return du + 1, x
                dq.append(v)
    return None, None


def lam(H, j, window_mult=3):
    """Return the shortest signed transfer length for one-indexed pass ``j``."""
    if j < 2:
        return None, None
    return signed_len(H[j - 1], H[: j - 1], window_mult * H[0] + H[j - 1])


def beta_exact(H, n, s):
    """Return the exact prefix phase defect and a minimizing character."""
    best = bk = None
    for k in range(1, n):
        m = 0
        for j in range(s):
            r = (k * H[j]) % n
            v = min(r, n - r)
            if v > m:
                m = v
            if best is not None and m >= best:
                break
        if best is None or m < best:
            best, bk = m, k
    return Fraction(best, n), bk


def tau_cover(H, n, s):
    """Return the signed word-metric covering radius on ``Z/n``."""
    INF = float("inf")
    d = [INF] * n
    d[0] = 0
    dq = deque([0])
    while dq:
        u = dq.popleft()
        for j in range(s):
            for v in ((u + H[j]) % n, (u - H[j]) % n):
                if d[v] == INF:
                    d[v] = d[u] + 1
                    dq.append(v)
    return max(d)


def pos_len(m, H, j):
    """Return the shortest positive representation length of ``m*h_j``."""
    target = m * H[j - 1]
    if target == 0:
        return 0
    INF = float("inf")
    d = [INF] * (target + 1)
    d[0] = 0
    for v in range(1, target + 1):
        for g in H[: j - 1]:
            if g <= v and d[v - g] + 1 < d[v]:
                d[v] = d[v - g] + 1
    return None if d[target] == INF else d[target]


def ray_quotient(H, n, j):
    """Return ``(M_j, Q_j, G_j, D_j, g_j)`` for one-indexed pass ``j``."""
    h = H[j - 1]
    M = (n - 1) // h
    prev = H[: j - 1]
    r = sg_reach(prev, n) if prev else [x == 0 for x in range(n + 1)]
    Q = [m for m in range(M + 1) if r[m * h]]
    G = [m for m in range(1, M + 1) if not r[m * h]]
    return M, Q, G, sum(n - m * h for m in G), len(G)


def local_apery_phase_bound(H, n, j):
    """Return the best local Apéry phase constant ``L(1+t)``.

    The search ranges over feasible moduli ``a >= 2`` in the ray quotient.
    The result is ``(L(1+t), a, L, t)``, or ``None`` when no certificate is
    available in the truncated quotient.
    """
    M, Q, _, _, _ = ray_quotient(H, n, j)
    best = None
    for a in [q for q in Q if q >= 2]:
        L, ok = 0, True
        for r in range(a):
            ls = [pos_len(m, H, j) for m in Q if m % a == r]
            ls = [x for x in ls if x is not None]
            if not ls:
                ok = False
                break
            L = max(L, min(ls))
        if not ok:
            continue
        w1 = [m for m in Q if m % a == 1]
        if not w1:
            continue
        t = (min(w1) - 1) // a
        cand = (L * (1 + t), a, L, t)
        if best is None or cand[0] < best[0]:
            best = cand
    return best


def three_smooth(n):
    """Return the decreasing Pratt grid ``2^a 3^b < n``."""
    out = []
    p = 1
    while p < n:
        q = p
        while q < n:
            out.append(q)
            q *= 3
        p *= 2
    return sorted(set(out), reverse=True)


def fib_gaps(n):
    """Return decreasing Fibonacci gaps below ``n``, starting from 1 and 2."""
    f = [1, 2]
    while f[-1] < n:
        f.append(f[-1] + f[-2])
    return [x for x in reversed(f) if x < n]


def random_gaps(n, seed=0, lo=3, hi=7):
    """Return a seeded decreasing schedule ending in 1."""
    rng = random.Random(seed)
    k = rng.randint(lo, hi)
    k = min(k, max(1, n - 3))
    return sorted(rng.sample(range(2, n), k), reverse=True) + [1]


def apery_genus_sylvester(gens, a, N=6000):
    """Return genus and first Sylvester sum from a complete Apéry set."""
    v = apery_set(gens, a, N)
    if v is None or any(v[r] is None for r in range(a)):
        return None
    vals = [v[r] for r in range(a)]
    sv = sum(vals)
    g = Fraction(sv, a) - Fraction(a - 1, 2)
    n1 = (
        Fraction(sum(x * x for x in vals), 2 * a)
        - Fraction(sv, 2)
        + Fraction(a * a - 1, 12)
    )
    return g, n1
